# app/core/audit/audit_actions.py

class AuditAction:
    CREATED = "CREATED"
    UPDATED = "UPDATED"
    DELETED = "DELETED"
    STATUS_CHANGED = "STATUS_CHANGED"
    FLAG_UPDATED = "FLAG_UPDATED"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    LOGIN_FAILED = "LOGIN_FAILED"
    REFRESH_FAILED = "REFRESH_FAILED"
    REFRESH_SUCCESS = "REFRESH_SUCCESS"
