export const PRODUCT_GROUP_OPTIONS = Object.freeze([
	{ value: "1001", text: "1001 - Cabos PVC 70 °C" },
	{ value: "1002", text: "1002 - Cabos PVC 105 °C" },
	{ value: "1003", text: "1003 - Cabos EPR 130 °C" },
	{ value: "1004", text: "1004 - Cabos Paralelos PVC" },
	{ value: "1005", text: "1005 - Cabos Silicone alta temperatura" },
	{ value: "1006", text: "1006 - Cabos PP com plug montado" },
	{ value: "1007", text: "1007 - Cabos PP sem plug" },
	{ value: "1008", text: "1008 - Terminais elétricos" },
	{ value: "1009", text: "1009 - Conectores, insertos e isoladores" },
	{ value: "1010", text: "1010 - Condutores elétricos rígidos (PVC)" },
	{ value: "1011", text: "1011 - Etiquetas técnicas e identificação" },
	{ value: "1012", text: "1012 - Tubos isolantes, corrugados e espaguetes" },
	{ value: "1013", text: "1013 - Termoencolhível em rolo" },
	{ value: "1014", text: "1014 - Componentes eletromecânicos diversos" },
	{ value: "1015", text: "1015 - Prensa-cabos" },
	{ value: "1016", text: "1016 - Resistores" },
	{ value: "1017", text: "1017 - Materiais auxiliares e insumos de produção" },
	{ value: "1019", text: "1019 - Componentes elétricos e mecânicos diversos" },
	{ value: "1020", text: "1020 - Carretéis e suportes plásticos" },
	{ value: "1021", text: "1021 - Diversos (uso geral / legado)" },
	{ value: "1025", text: "1025 - Termistores e sensores térmicos" },
	{ value: "1032", text: "1032 - Fixadores, ferragens e componentes mecânicos" },
	{ value: "1035", text: "1035 - Abraçadeiras e elementos de amarração" },
	{ value: "1036", text: "1036 - Cabos EPR alta temperatura" },
	{ value: "1037", text: "1037 - Cabos EPR LM para motores elétricos" },
	{ value: "1038", text: "1038 - Cabos EPR para aplicações industriais" },
	{ value: "1039", text: "1039 - Condutores de cobre nu e esmaltado" },
	{ value: "1040", text: "1040 - Cabos silicone alta temperatura (SIL / Vitrosilicone)" },
	{ value: "1041", text: "1041 - Cabos de ignição e alta tensão" },
	{ value: "1042", text: "1042 - Cabos multicondutores especiais" },
	{ value: "1043", text: "1043 - Cabos flat (PVC)" },
	{ value: "1044", text: "1044 - Cabos em fluoropolímero (PTFE / Teflon)" },
	{ value: "1045", text: "1045 - Equipamentos e dispositivos de apoio fabril" },
	{ value: "1046", text: "1046 - Cabos especiais (cadastro residual)" },
	{ value: "1047", text: "1047 - Cabos silicone automotivos / numerados" },
	{ value: "1048", text: "1048 - Cordoalhas e condutores de cobre" },
	{ value: "1049", text: "1049 - Cabos especiais com normas internacionais" },
	{ value: "1050", text: "1050 - Termoencolhível e tubos cortados" },
	{ value: "1051", text: "1051 - Tubos especiais diversos" },
	{ value: "1052", text: "1052 - Compostos, tintas e insumos químicos" },
	{ value: "1053", text: "1053 - Cabos poliéster e materiais especiais" },
	{ value: "1055", text: "1055 - Cabos XLPO e fibras ópticas" },
]);


export const UNIT_OPTIONS = Object.freeze([
	{ value: "PC", text: "PC - PECA" },
	{ value: "UN", text: "UN - UNIDADE" },
	{ value: "MM", text: "MM - MILÍMETRO" },
	{ value: "MT", text: "MT - METRO" },
	{ value: "L", text: "L - LITRO" },
	{ value: "G", text: "G - GRAMA" },
	{ value: "KG", text: "KG - QUILOGRAMA" },
	{ value: "MI", text: "MI - MILHEIROS" },
	{ value: "MI", text: "MI - MIL" },
	{ value: "CX", text: "CX - CAIXA" },
	{ value: "FD", text: "FD - FARDO" },
	{ value: "GL", text: "GL - GALAO" },
	{ value: "JG", text: "JG - JOGO" },
	{ value: "P", text: "P - PAR" },
	{ value: "RL", text: "RL - ROLO" },
	{ value: "RS", text: "RS - RESMA" },
]);

export const WAREHOUSE_OPTIONS = Object.freeze([
	{ value: "01", text: "01 - Almoxarifado" },
	{ value: "99", text: "99 - Fábrica" },
]);

export const YES_NO_OPTIONS = Object.freeze([
	{ value: "1", text: "NÃO" },
	{ value: "2", text: "SIM" },
]);

export const DEFAULT_VALUES = Object.freeze({
	TIPO: "MP",
	CTA_CONTABIL: "11401002",
	ARMAZEM_PADRAO: "01",
	PRODUTO_TERCEIRO: "1",
});
